spring.application.name=todo

# TEMP: disable DB for deployment
# Comment these lines
# spring.datasource.url=...
# spring.datasource.username=...
# spring.datasource.password=...

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=update

# IMPORTANT for Render
server.port=${PORT:8080}

# move secrets later
jwt.secret=your_secret
jwt.expiration=86400000