spring.application.name=todo

# TEMP: disable DB for deployment
# spring.datasource.url=jdbc:mysql://localhost:3306/todo_app
# spring.datasource.username=root
# spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update

# IMPORTANT for Render
server.port=${PORT:8080}

# move secrets later
jwt.secret=your_secret
jwt.expiration=86400000